apiVersion: v1
kind: PersistentVolume
metadata:
  name: www-data
  labels:
    type: manual
spec:
  capacity:
    storage: {{ .Values.persistence.size }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  {{- if .Values.persistence.storageClassName }}
  storageClassName: {{ .Values.persistence.storageClassName }}
  {{- end }}
  hostPath:
    path: /mnt/data/www-data
